use_frameworks!

platform :ios, '8.0'

target 'FSAttendanceTable_Example' do
  pod 'FSAttendanceTable', :path => '../'

  target 'FSAttendanceTable_Tests' do
    inherit! :search_paths

    
  end
end
